### ISSUE TITLE
Async Observable

### ISSUE THREAD

**Issue by hchoong** [s2501/ng-2-lab-es5#1]
Trying to implement the async on the search function. But resulted on 
`TypeError: Cannot read property '$$observable' of undefined`

Do you know how can I apply the async in es5?

**Comment by hchoong** [comment]
After debugging the code, found out that there is a bug on the core.umd.js when not using AMD loader. FYI, https://github.com/angular/angular/issues/14473

**Comment by s2501** [comment]
Check this commit 
https://github.com/s2501/ng-2-lab-es5/commit/719d09d33e0b3b31daf6efb70a3798264efe86d4
this is the point in which I was able to have observables and be working with RX
I remember how much trouble I had while I found my way around, last year
play and tinker with my repo and you should be able to have it running 
personal advice: switch to typescript, ES5 is not the way to write Angular 2+

**Comment by hchoong** [comment]
@s2501 Thank you for the advice. The fact that the advantage on development with typescript compare to ES5 is unbeatable. was trying to explore the possibilities of not using any compilers for the app. Nowadays not much latest frameworks support ES5 polyfill or compability like Angular 2+ team does.

**Comment by s2501** [comment]
@hchoong even if you don't use compilers, still you need to have all the angular 2+ JS libraries in xMB size, while with compilers and TypeScript, there's some magic involved for appropriate inclusion of the dependencies which you use in the application.
X)
